### ISSUE TITLE
Move this linter to be under click-contrib

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/flake8-click#1]
@untitaker: I have been chatting with @davidism on https://discordapp.com/channels/531221516914917387/531221879709630498, about moving to this to be under to be under click-contrib. Please advise on how if you think its ok!

**Comment by untitaker** [comment]
@ulziibay deep links into discord are broken because I have no access to that server, but I have invited you to that organization. You should be able to join it.

**Comment by ulziibay** [comment]
Thank you sir!

**Comment by ulziibay** [comment]
@untitaker should I fork this over or just copy-paste and do development there? I do not have strong thoughts either way. let me know how people did in the past!

**Comment by untitaker** [comment]
You can move/transfer the repo in your repo settings. The old URLs will redirect.

**Comment by ulziibay** [comment]
Decided on not moving over for now!
