### ISSUE TITLE
click `option-function-argument-check` falsely fires when `expose_value=False`

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/flake8-click#8]
`expose_value` can be used in a click option to prevent sending the option value to the command function intentionally. In this case, we should not raise a finding.

See https://github.com/pallets/flask/blob/master/src/flask/cli.py line 785.

**Comment by minusworld** [comment]
Thanks! I ran a job on platform yesterday that highlighted some other FPs, but I didn't see this one.
